### ISSUE TITLE
Fail seek

### ISSUE THREAD

**Issue by ComandPromt** [fa7ad/dumb-player#16]
Hello, the video cannot be played from any second, the seek always starts at the beginning of the video. When selecting down in the slider, the video cannot be played from the middle, it always starts playing from the beginning

**Comment by fa7ad** [comment]
Hi, try dragging the progress bar indicator to the middle instead of clicking the middle

**Comment by ComandPromt** [comment]
> Hi, try dragging the progress bar indicator to the middle instead of clicking the middle

Thanks, but it only works from the second half of the video, the first half follows the same problem
